### ISSUE TITLE
is Typescript React Code NOT supported ?

### ISSUE THREAD

**Issue by WellerQu** [ambar/vscode-live-code#1]
I like your idea of the plugin in vscode. But I found a question about the TypeScript React code(tsx). You may follow the below steps to reproduce the question.

1. press CMD + N to open a new file. (Do not save it)
2. select the file type to TypeScript React.
3. write the code like this:
 
```typescript
interface SomeProps {
  a: number
}

const Some = (props: SomeProps) => {
  return (
    <div>{ props.a }</div>
  )
}

  ; <Some a={ 1 } />
```

Now, You may get the error:

> [Error: Build failed with 1 error:
<Untitled>:1:10: error: Expected ";" but found "SomeProps"]

**Comment by ambar** [comment]
@WellerQu Nice catch, fixed in v0.0.6.
